---

- name: Copy atomic update challenge/response script
  copy:
    src: yubikey-atomic-update-challenge
    dest: "{{ yubi2factor_script_update_challenge }}"
    mode: 0755


- name: Create cron for challenge response creation for root.
  cron:
    name: yubi2factor_script_update_challenge
    job: "{{ yubi2factor_script_update_challenge }}"
    minute: 42
    hour: "*/4"

- name: Create cron for challenge response creation for {{ username }}.
  cron:
    name: yubi2factor_script_update_challenge
    job: "{{ yubi2factor_script_update_challenge }} >> {{ yubi2factor_cron_update_challenge_log }} 2>&1"
    user: "{{ username }}"
    minute: 42
    hour: "*/4"
