#!/bin/bash
#
# Perform a atomic update of yubikey challenge/response file

set -o nounset
set -o errexit
set -o pipefail

# log current date
date --iso-8601=m

mkdir -p "$HOME/.yubico"
cd "$HOME/.yubico"

yubikey_id="$( ykinfo -sq )"

# with param '-p "."' ykpamcfg creates a file containing user, instead of default
ykpamcfg -p "."

# now move file to default location
mv --update --force "$USER-$yubikey_id" "challenge-$yubikey_id"
